# Generated by Django 3.2.9 on 2021-11-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_auto_20211128_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='collaborator_ids',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='follower_ids',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sharing_agreement_ids',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='via',
        ),
        migrations.AddField(
            model_name='ticket',
            name='allow_attachments',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='allow_channelback',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='brand_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='generated_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_form_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignee_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='satisfaction_rating',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitter_id',
            field=models.IntegerField(),
        ),
    ]
