# Generated by Django 3.2.9 on 2021-11-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_auto_20211128_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='allow_attachments',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='allow_channelback',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='brand_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='has_incidents',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='raw_subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='recipient',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='satisfaction_rating',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitter_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_form_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
