# Generated by Django 3.2.9 on 2021-11-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_auto_20211128_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='problem_id',
            field=models.IntegerField(null=True),
        ),
    ]
