# Generated by Django 3.2.9 on 2021-11-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_alter_ticket_problem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='allow_channelback',
            new_name='allow_channel_back',
        ),
    ]
