# Generated by Django 3.2.9 on 2021-11-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0006_rename_allow_channelback_ticket_allow_channel_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='allow_attachments',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='allow_channel_back',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='generated_timestamp',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_form_id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='satisfaction_rating',
            field=models.JSONField(null=True),
        ),
    ]
